package com.example.workbench.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGE,
    WORKSPACE_CREATE,
    WORKSPACE_MEMBER_ADD,
    WORKSPACE_MEMBER_ROLE_CHANGE,
    WORKSPACE_MEMBER_REMOVE,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    USER_ROLE_CHANGE,
    MODEL_CONFIG_CREATE,
    MODEL_CONFIG_UPDATE,
    MODEL_CONFIG_DELETE,
    MODEL_CONFIG_DEFAULT_CHANGE,
    PERSONAL_MODEL_CONFIG_CHANGE,
    AUDIT_LOG_DELETE
}
