package com.example.workbench.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGE,
    WORKSPACE_CREATE,
    WORKSPACE_MEMBER_ADD,
    WORKSPACE_MEMBER_ROLE_CHANGE,
    WORKSPACE_MEMBER_REMOVE,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    DOCUMENT_REBUILD,
    USER_ROLE_CHANGE,
    MODEL_CONFIG_CREATE,
    MODEL_CONFIG_UPDATE,
    MODEL_CONFIG_DELETE,
    MODEL_CONFIG_DEFAULT_CHANGE,
    PERSONAL_MODEL_CONFIG_CHANGE,
    SYSTEM_LOG_CLEAR,
    /** Agent 发起且无法归入上面具体动作的系统级写操作。 */
    SYSTEM_AGENT_ACTION,
    AUDIT_LOG_DELETE
}
